import type { Metadata } from "next";
import Header from "@/components/Header/Header";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body >
        <Header />
        <main>
          {children}

        </main>
      </body>
    </html>
  );
}

export default RootLayout;
