import type { Metadata } from "next";
import Header from "@/components/Header/Header";
import './globals.scss'
import "@fortawesome/fontawesome-svg-core/styles.css"
import { kanit, montserrat } from "@/font";
import { availableLocales } from "@/utils/i18n";
import { Locale } from "@/utils/i18n-config";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.png'
  }
};

export function generateStaticParams() {
  return availableLocales.map(locale => ({ locale, }));
}

const RootLayout = ({
  children, params: { locale }
}: Readonly<{
  children: React.ReactNode, params: { locale: Locale }
}>) => {


  return (
    <html lang="en">
      <body className={`${kanit.variable} ${montserrat.variable}`}>
        <Header locale={locale} />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}

export default RootLayout;
