import type { Metadata } from "next";
import Header from "@/components/Header/Header";
import './globals.scss'
import "@fortawesome/fontawesome-svg-core/styles.css"
import { kanit, montserrat } from "@/font";
import { availableLocales } from "@/utils/i18n";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return availableLocales.map(locale => ({ locale, }));
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`${kanit.variable} ${montserrat.variable}`}>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}

export default RootLayout;
